FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

ENV NODE_ENV=development
ENV EXPO_USE_FAST_RESOLVER=true

EXPOSE 8081

CMD ["npm", "run", "start"]
